name: Create Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight UTC

env:
  REPO_NAME: ${{ github.repository }}
  CHANGELOG: ''
  DEFAULT_BUMP_TYPE: patch

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version_check.outputs.new_version }}
      current_version: ${{ steps.version_check.outputs.current_version }}
      release_created: ${{ steps.create_release.outputs.release_created }}
    env:
      BUMP_TYPE: ''
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for changelog generation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set bump type
        id: set_bump_type
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "BUMP_TYPE=${{ github.event.inputs.bump_type }}" >> $GITHUB_ENV
          else
            echo "BUMP_TYPE=${{ env.DEFAULT_BUMP_TYPE }}" >> $GITHUB_ENV
          fi

      - name: Bump version
        id: version_check
        run: |
          make version-bump TYPE=${{ env.BUMP_TYPE }}
          NEW_VERSION=$(cat VERSION)
          SETUP_VERSION=$(grep -Po "(?<=version=\")[^\"]*" setup.py)

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "current_version=$SETUP_VERSION" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        if: steps.version_check.outputs.new_version != ''
        id: changelog
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          chmod +x .github/scripts/generate_changelog.sh
          CHANGELOG=$(.github/scripts/generate_changelog.sh --version ${{ steps.version_check.outputs.new_version }})
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Commit version bump
        if: steps.version_check.outputs.new_version != ''
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION setup.py
          git commit -m "chore: bump version to ${{ steps.version_check.outputs.new_version }}"
          git push

      - name: Create Release
        if: steps.version_check.outputs.new_version != ''
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v${{ steps.version_check.outputs.new_version }}
          release_name: Release v${{ steps.version_check.outputs.new_version }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
        continue-on-error: true

      - name: Clean up on failure
        if: failure() && steps.version_check.outputs.new_version != ''
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          # Delete the tag if it was created
          git push --delete origin v${{ steps.version_check.outputs.new_version }} || true

          # Revert version changes
          git checkout HEAD^ VERSION setup.py
          git commit -m "revert: version bump changes"
          git push -f

  publish:
    needs: check-and-release
    if: needs.check-and-release.outputs.release_created == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          twine upload dist/*
